matchTiles=gregtech:iconsets/TM_TESLA_WINDING_SECONDARY_SIDES gregtech:iconsets/TM_TESLA_WINDING_SECONDARY_TOP_BOTTOM
method=ctm
faces=all
tiles=0 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
connect=block
