pause
set list=ore oreSmall ore_OVERLAY oreSmall_OVERLAY
for %%a in (%list%) do (
    COPY %%a.png "materialicons\DIAMOND\"
    COPY %%a.png "materialicons\DULL\"
    COPY %%a.png "materialicons\EMERALD\"
    COPY %%a.png "materialicons\ENRICHED\"
    COPY %%a.png "materialicons\FIERY\"
    COPY %%a.png "materialicons\FINE\"
    COPY %%a.png "materialicons\FLINT\"
    COPY %%a.png "materialicons\FLUID\"
    COPY %%a.png "materialicons\GEM_A\"
    COPY %%a.png "materialicons\GEM_HORIZONTAL\"
    COPY %%a.png "materialicons\GEM_VERTICAL\"
    COPY %%a.png "materialicons\GLASS\"
    COPY %%a.png "materialicons\LAPIS\"
    COPY %%a.png "materialicons\LEAF\"
    COPY %%a.png "materialicons\LIGNITE\"
    COPY %%a.png "materialicons\MAGNETIC\"
    COPY %%a.png "materialicons\METALLIC\"
    COPY %%a.png "materialicons\NETHERSTAR\"
    COPY %%a.png "materialicons\NONE\"
    COPY %%a.png "materialicons\NUCLEAR\"
    COPY %%a.png "materialicons\OPAL\"
    COPY %%a.png "materialicons\PAPER\"
    COPY %%a.png "materialicons\POWDER\"
    COPY %%a.png "materialicons\QUARTZ\"
    COPY %%a.png "materialicons\REFINED\"
    COPY %%a.png "materialicons\ROUGH\"
    COPY %%a.png "materialicons\RUBY\"
    COPY %%a.png "materialicons\SAND\"
    COPY %%a.png "materialicons\SHARDS\"
    COPY %%a.png "materialicons\SHINY\"
    :: COPY %%a.png "materialicons\WOOD\"
    COPY %%a.png "materialicons\CUSTOM\awakeneddraconium"
    COPY %%a.png "materialicons\CUSTOM\cosmicneutronium"
    COPY %%a.png "materialicons\CUSTOM\crystalline"
    COPY %%a.png "materialicons\CUSTOM\darksteel"
    COPY %%a.png "materialicons\CUSTOM\draconium"
    COPY %%a.png "materialicons\CUSTOM\energetic"
    COPY %%a.png "materialicons\CUSTOM\ichorium"
    COPY %%a.png "materialicons\CUSTOM\Manasteel"
    COPY %%a.png "materialicons\CUSTOM\melodic"
    COPY %%a.png "materialicons\CUSTOM\stellar"
    COPY %%a.png "materialicons\CUSTOM\vibrant"
    COPY %%a.png "materialicons\CUSTOM\vivid"
)