pause
set list=Side Tiny Small Medium Large Huge Quadruple Nonuple
for %%a in (%list%) do (
    COPY pipe%%a.png "materialicons\DIAMOND\"
    COPY pipe%%a.png "materialicons\DULL\"
    COPY pipe%%a.png "materialicons\EMERALD\"
    COPY pipe%%a.png "materialicons\ENRICHED\"
    COPY pipe%%a.png "materialicons\FIERY\"
    COPY pipe%%a.png "materialicons\FINE\"
    COPY pipe%%a.png "materialicons\FLINT\"
    COPY pipe%%a.png "materialicons\FLUID\"
    COPY pipe%%a.png "materialicons\GEM_A\"
    COPY pipe%%a.png "materialicons\GEM_HORIZONTAL\"
    COPY pipe%%a.png "materialicons\GEM_VERTICAL\"
    COPY pipe%%a.png "materialicons\GLASS\"
    COPY pipe%%a.png "materialicons\LAPIS\"
    :: COPY pipe%%a.png "materialicons\LEAF\"
    COPY pipe%%a.png "materialicons\LIGNITE\"
    COPY pipe%%a.png "materialicons\MAGNETIC\"
    COPY pipe%%a.png "materialicons\METALLIC\"
    COPY pipe%%a.png "materialicons\NETHERSTAR\"
    COPY pipe%%a.png "materialicons\NONE\"
    COPY pipe%%a.png "materialicons\NUCLEAR\"
    COPY pipe%%a.png "materialicons\OPAL\"
    COPY pipe%%a.png "materialicons\PAPER\"
    COPY pipe%%a.png "materialicons\POWDER\"
    COPY pipe%%a.png "materialicons\QUARTZ\"
    :: COPY pipe%%a.png "materialicons\REFINED\"
    COPY pipe%%a.png "materialicons\ROUGH\"
    COPY pipe%%a.png "materialicons\RUBY\"
    COPY pipe%%a.png "materialicons\SAND\"
    COPY pipe%%a.png "materialicons\SHARDS\"
    COPY pipe%%a.png "materialicons\SHINY\"
    :: COPY pipe%%a.png "materialicons\WOOD\"
    COPY pipe%%a.png "materialicons\CUSTOM\awakeneddraconium\"
    :: COPY pipe%%a.png "materialicons\CUSTOM\bedrockium\"
    COPY pipe%%a.png "materialicons\CUSTOM\crystalline\"
    COPY pipe%%a.png "materialicons\CUSTOM\darksteel\"
    COPY pipe%%a.png "materialicons\CUSTOM\draconium\"
    COPY pipe%%a.png "materialicons\CUSTOM\energetic\"
    COPY pipe%%a.png "materialicons\CUSTOM\ichorium\"
    :: COPY pipe%%a.png "materialicons\CUSTOM\infinity\"
    COPY pipe%%a.png "materialicons\CUSTOM\Manasteel\"
    COPY pipe%%a.png "materialicons\CUSTOM\melodic\"
    :: COPY pipe%%a.png "materialicons\CUSTOM\spacetime\"
    COPY pipe%%a.png "materialicons\CUSTOM\stellar\"
    COPY pipe%%a.png "materialicons\CUSTOM\vibrant\"
    COPY pipe%%a.png "materialicons\CUSTOM\vivid\"  
)