pause
COPY wire.png "materialicons\DIAMOND\"
COPY wire.png "materialicons\DULL\"
COPY wire.png "materialicons\EMERALD\"
COPY wire.png "materialicons\ENRICHED\"
COPY wire.png "materialicons\FIERY\"
COPY wire.png "materialicons\FINE\"
COPY wire.png "materialicons\FLINT\"
COPY wire.png "materialicons\FLUID\"
COPY wire.png "materialicons\GEM_A\"
COPY wire.png "materialicons\GEM_HORIZONTAL\"
COPY wire.png "materialicons\GEM_VERTICAL\"
COPY wire.png "materialicons\GLASS\"
COPY wire.png "materialicons\LAPIS\"
COPY wire.png "materialicons\LEAF\"
COPY wire.png "materialicons\LIGNITE\"
COPY wire.png "materialicons\MAGNETIC\"
COPY wire.png "materialicons\METALLIC\"
COPY wire.png "materialicons\NETHERSTAR\"
COPY wire.png "materialicons\NONE\"
COPY wire.png "materialicons\NUCLEAR\"
COPY wire.png "materialicons\OPAL\"
COPY wire.png "materialicons\PAPER\"
COPY wire.png "materialicons\POWDER\"
COPY wire.png "materialicons\QUARTZ\"
COPY wire.png "materialicons\REFINED\"
COPY wire.png "materialicons\ROUGH\"
COPY wire.png "materialicons\RUBY\"
COPY wire.png "materialicons\SAND\"
COPY wire.png "materialicons\SHARDS\"
COPY wire.png "materialicons\SHINY\"
COPY wire.png "materialicons\WOOD\"
COPY wire.png "materialicons\CUSTOM\awakeneddraconium\"
:: COPY wire.png "materialicons\CUSTOM\bedrockium\"
COPY wire.png "materialicons\CUSTOM\crystalline\"
COPY wire.png "materialicons\CUSTOM\darksteel\"
COPY wire.png "materialicons\CUSTOM\draconium\"
COPY wire.png "materialicons\CUSTOM\energetic\"
COPY wire.png "materialicons\CUSTOM\ichorium\"
:: COPY wire.png "materialicons\CUSTOM\infinity\"
COPY wire.png "materialicons\CUSTOM\Manasteel\"
COPY wire.png "materialicons\CUSTOM\melodic\"
:: COPY wire.png "materialicons\CUSTOM\spacetime\"
COPY wire.png "materialicons\CUSTOM\stellar\"
COPY wire.png "materialicons\CUSTOM\vibrant\"
COPY wire.png "materialicons\CUSTOM\vivid\"