pause

COPY emerald.png "materialicons\DIAMOND\block1.png"
COPY redstone.png "materialicons\DIAMOND\block2.png"
COPY emerald.png "materialicons\DIAMOND\block3.png"
COPY lapis.png "materialicons\DIAMOND\block4.png"
COPY iron.png "materialicons\DIAMOND\block5.png"
COPY diamond.png "materialicons\DIAMOND\block6.png"

COPY diamond.png "materialicons\DULL\block1.png"
COPY redstone.png "materialicons\DULL\block2.png"
COPY emerald.png "materialicons\DULL\block3.png"
COPY lapis.png "materialicons\DULL\block4.png"
COPY iron.png "materialicons\DULL\block5.png"
COPY diamond.png "materialicons\DIAMOND\block6.png"

COPY emerald.png "materialicons\EMERALD\block1.png"
COPY redstone.png "materialicons\EMERALD\block2.png"
COPY emerald.png "materialicons\EMERALD\block3.png"
COPY lapis.png "materialicons\EMERALD\block4.png"
COPY iron.png "materialicons\EMERALD\block5.png"
COPY diamond.png "materialicons\EMERALD\block6.png"

COPY diamond.png "materialicons\ENRICHED\block1.png"
COPY redstone.png "materialicons\ENRICHED\block2.png"
COPY emerald.png "materialicons\ENRICHED\block3.png"
COPY lapis.png "materialicons\ENRICHED\block4.png"
COPY iron.png "materialicons\ENRICHED\block5.png"
COPY diamond.png "materialicons\ENRICHED\block6.png"

COPY diamond.png "materialicons\FIERY\block1.png"
COPY redstone.png "materialicons\FIERY\block2.png"
COPY emerald.png "materialicons\FIERY\block3.png"
COPY lapis.png "materialicons\FIERY\block4.png"
COPY iron.png "materialicons\FIERY\block5.png"
COPY diamond.png "materialicons\FIERY\block6.png"

COPY redstone.png "materialicons\FINE\block1.png"
COPY redstone.png "materialicons\FINE\block2.png"
COPY emerald.png "materialicons\FINE\block3.png"
COPY lapis.png "materialicons\FINE\block4.png"
COPY iron.png "materialicons\FINE\block5.png"
COPY diamond.png "materialicons\FINE\block6.png"

COPY redstone.png "materialicons\FLINT\block1.png"
COPY redstone.png "materialicons\FLINT\block2.png"
COPY emerald.png "materialicons\FLINT\block3.png"
COPY lapis.png "materialicons\FLINT\block4.png"
COPY iron.png "materialicons\FLINT\block5.png"
COPY diamond.png "materialicons\FLINT\block6.png"

COPY diamond.png "materialicons\FLUID\block1.png"
COPY redstone.png "materialicons\FLUID\block2.png"
COPY emerald.png "materialicons\FLUID\block3.png"
COPY lapis.png "materialicons\FLUID\block4.png"
COPY iron.png "materialicons\FLUID\block5.png"
COPY diamond.png "materialicons\FLUID\block6.png"

COPY emerald.png "materialicons\GEM_A\block1.png"
COPY redstone.png "materialicons\GEM_A\block2.png"
COPY emerald.png "materialicons\GEM_A\block3.png"
COPY lapis.png "materialicons\GEM_A\block4.png"
COPY iron.png "materialicons\GEM_A\block5.png"
COPY diamond.png "materialicons\GEM_A\block6.png"

COPY emerald.png "materialicons\GEM_HORIZONTAL\block1.png"
COPY redstone.png "materialicons\GEM_HORIZONTAL\block2.png"
COPY emerald.png "materialicons\GEM_HORIZONTAL\block3.png"
COPY lapis.png "materialicons\GEM_HORIZONTAL\block4.png"
COPY iron.png "materialicons\GEM_HORIZONTAL\block5.png"
COPY diamond.png "materialicons\GEM_HORIZONTAL\block6.png"

COPY emerald.png "materialicons\GEM_VERTICAL\block1.png"
COPY redstone.png "materialicons\GEM_VERTICAL\block2.png"
COPY emerald.png "materialicons\GEM_VERTICAL\block3.png"
COPY lapis.png "materialicons\GEM_VERTICAL\block4.png"
COPY iron.png "materialicons\GEM_VERTICAL\block5.png"
COPY diamond.png "materialicons\GEM_VERTICAL\block6.png"

COPY emerald.png "materialicons\GLASS\block1.png"
COPY redstone.png "materialicons\GLASS\block2.png"
COPY emerald.png "materialicons\GLASS\block3.png"
COPY lapis.png "materialicons\GLASS\block4.png"
COPY iron.png "materialicons\GLASS\block5.png"
COPY diamond.png "materialicons\GLASS\block6.png"

COPY lapis.png "materialicons\LAPIS\block1.png"
COPY redstone.png "materialicons\LAPIS\block2.png"
COPY emerald.png "materialicons\LAPIS\block3.png"
COPY lapis.png "materialicons\LAPIS\block4.png"
COPY iron.png "materialicons\LAPIS\block5.png"
COPY diamond.png "materialicons\LAPIS\block6.png"

COPY wood.png "materialicons\LEAF\block1.png"
COPY redstone.png "materialicons\LEAF\block2.png"
COPY emerald.png "materialicons\LEAF\block3.png"
COPY lapis.png "materialicons\LEAF\block4.png"
COPY iron.png "materialicons\LEAF\block5.png"
COPY diamond.png "materialicons\LEAF\block6.png"

COPY redstone.png "materialicons\LIGNITE\block1.png"
COPY redstone.png "materialicons\LIGNITE\block2.png"
COPY emerald.png "materialicons\LIGNITE\block3.png"
COPY lapis.png "materialicons\LIGNITE\block4.png"
COPY iron.png "materialicons\LIGNITE\block5.png"
COPY diamond.png "materialicons\LIGNITE\block6.png"

COPY diamond.png "materialicons\MAGNETIC\block1.png"
COPY redstone.png "materialicons\MAGNETIC\block2.png"
COPY emerald.png "materialicons\MAGNETIC\block3.png"
COPY lapis.png "materialicons\MAGNETIC\block4.png"
COPY iron.png "materialicons\MAGNETIC\block5.png"
COPY diamond.png "materialicons\MAGNETIC\block6.png"

COPY diamond.png "materialicons\METALLIC\block1.png"
COPY redstone.png "materialicons\METALLIC\block2.png"
COPY emerald.png "materialicons\METALLIC\block3.png"
COPY lapis.png "materialicons\METALLIC\block4.png"
COPY iron.png "materialicons\METALLIC\block5.png"
COPY diamond.png "materialicons\METALLIC\block6.png"

COPY emerald.png "materialicons\NETHERSTAR\block1.png"
COPY redstone.png "materialicons\NETHERSTAR\block2.png"
COPY emerald.png "materialicons\NETHERSTAR\block3.png"
COPY lapis.png "materialicons\NETHERSTAR\block4.png"
COPY iron.png "materialicons\NETHERSTAR\block5.png"
COPY diamond.png "materialicons\NETHERSTAR\block6.png"

COPY diamond.png "materialicons\NONE\block1.png"
COPY redstone.png "materialicons\NONE\block2.png"
COPY emerald.png "materialicons\NONE\block3.png"
COPY lapis.png "materialicons\NONE\block4.png"
COPY iron.png "materialicons\NONE\block5.png"
COPY diamond.png "materialicons\NONE\block6.png"

COPY diamond.png "materialicons\NUCLEAR\block1.png"
COPY redstone.png "materialicons\NUCLEAR\block2.png"
COPY emerald.png "materialicons\NUCLEAR\block3.png"
COPY lapis.png "materialicons\NUCLEAR\block4.png"
COPY iron.png "materialicons\NUCLEAR\block5.png"
COPY diamond.png "materialicons\NUCLEAR\block6.png"

COPY emerald.png "materialicons\OPAL\block1.png"
COPY redstone.png "materialicons\OPAL\block2.png"
COPY emerald.png "materialicons\OPAL\block3.png"
COPY lapis.png "materialicons\OPAL\block4.png"
COPY iron.png "materialicons\OPAL\block5.png"
COPY diamond.png "materialicons\OPAL\block6.png"

COPY lapis.png "materialicons\PAPER\block1.png"
COPY redstone.png "materialicons\PAPER\block2.png"
COPY emerald.png "materialicons\PAPER\block3.png"
COPY lapis.png "materialicons\PAPER\block4.png"
COPY iron.png "materialicons\PAPER\block5.png"
COPY diamond.png "materialicons\PAPER\block6.png"

COPY redstone.png "materialicons\POWDER\block1.png"
COPY redstone.png "materialicons\POWDER\block2.png"
COPY emerald.png "materialicons\POWDER\block3.png"
COPY lapis.png "materialicons\POWDER\block4.png"
COPY iron.png "materialicons\POWDER\block5.png"
COPY diamond.png "materialicons\POWDER\block6.png"

COPY diamond.png "materialicons\QUARTZ\block1.png"
COPY redstone.png "materialicons\QUARTZ\block2.png"
COPY emerald.png "materialicons\QUARTZ\block3.png"
COPY lapis.png "materialicons\QUARTZ\block4.png"
COPY iron.png "materialicons\QUARTZ\block5.png"
COPY diamond.png "materialicons\QUARTZ\block6.png"

COPY wood.png "materialicons\REFINED\block1.png"
COPY redstone.png "materialicons\REFINED\block2.png"
COPY emerald.png "materialicons\REFINED\block3.png"
COPY lapis.png "materialicons\REFINED\block4.png"
COPY iron.png "materialicons\REFINED\block5.png"
COPY diamond.png "materialicons\REFINED\block6.png"

COPY redstone.png "materialicons\ROUGH\block1.png"
COPY redstone.png "materialicons\ROUGH\block2.png"
COPY emerald.png "materialicons\ROUGH\block3.png"
COPY lapis.png "materialicons\ROUGH\block4.png"
COPY iron.png "materialicons\ROUGH\block5.png"
COPY diamond.png "materialicons\ROUGH\block6.png"

COPY emerald.png "materialicons\RUBY\block1.png"
COPY redstone.png "materialicons\RUBY\block2.png"
COPY emerald.png "materialicons\RUBY\block3.png"
COPY lapis.png "materialicons\RUBY\block4.png"
COPY iron.png "materialicons\RUBY\block5.png"
COPY diamond.png "materialicons\RUBY\block6.png"

COPY redstone.png "materialicons\SAND\block1.png"
COPY redstone.png "materialicons\SAND\block2.png"
COPY emerald.png "materialicons\SAND\block3.png"
COPY lapis.png "materialicons\SAND\block4.png"
COPY iron.png "materialicons\SAND\block5.png"
COPY diamond.png "materialicons\SAND\block6.png"

COPY emerald.png "materialicons\SHARDS\block1.png"
COPY redstone.png "materialicons\SHARDS\block2.png"
COPY emerald.png "materialicons\SHARDS\block3.png"
COPY lapis.png "materialicons\SHARDS\block4.png"
COPY iron.png "materialicons\SHARDS\block5.png"
COPY diamond.png "materialicons\SHARDS\block6.png"

COPY diamond.png "materialicons\SHINY\block1.png"
COPY redstone.png "materialicons\SHINY\block2.png"
COPY emerald.png "materialicons\SHINY\block3.png"
COPY lapis.png "materialicons\SHINY\block4.png"
COPY iron.png "materialicons\SHINY\block5.png"
COPY diamond.png "materialicons\SHINY\block6.png"

COPY wood.png "materialicons\WOOD\block1.png"
COPY redstone.png "materialicons\WOOD\block2.png"
COPY emerald.png "materialicons\WOOD\block3.png"
COPY lapis.png "materialicons\WOOD\block4.png"
COPY iron.png "materialicons\WOOD\block5.png"
COPY diamond.png "materialicons\WOOD\block6.png"

COPY diamond.png "materialicons\CUSTOM\awakeneddraconium\block1.png"
COPY redstone.png "materialicons\CUSTOM\awakeneddraconium\block2.png"
COPY emerald.png "materialicons\CUSTOM\awakeneddraconium\block3.png"
COPY lapis.png "materialicons\CUSTOM\awakeneddraconium\block4.png"
COPY iron.png "materialicons\CUSTOM\awakeneddraconium\block5.png"
COPY diamond.png "materialicons\CUSTOM\awakeneddraconium\block6.png"

COPY diamond.png "materialicons\CUSTOM\crystalline\block1.png"
COPY redstone.png "materialicons\CUSTOM\crystalline\block2.png"
COPY emerald.png "materialicons\CUSTOM\crystalline\block3.png"
COPY lapis.png "materialicons\CUSTOM\crystalline\block4.png"
COPY iron.png "materialicons\CUSTOM\crystalline\block5.png"
COPY diamond.png "materialicons\CUSTOM\crystalline\block6.png"

COPY diamond.png "materialicons\CUSTOM\darksteel\block1.png"
COPY redstone.png "materialicons\CUSTOM\darksteel\block2.png"
COPY emerald.png "materialicons\CUSTOM\darksteel\block3.png"
COPY lapis.png "materialicons\CUSTOM\darksteel\block4.png"
COPY iron.png "materialicons\CUSTOM\darksteel\block5.png"
COPY diamond.png "materialicons\CUSTOM\darksteel\block6.png"

COPY diamond.png "materialicons\CUSTOM\draconium\block1.png"
COPY redstone.png "materialicons\CUSTOM\draconium\block2.png"
COPY emerald.png "materialicons\CUSTOM\draconium\block3.png"
COPY lapis.png "materialicons\CUSTOM\draconium\block4.png"
COPY iron.png "materialicons\CUSTOM\draconium\block5.png"
COPY diamond.png "materialicons\CUSTOM\draconium\block6.png"

COPY diamond.png "materialicons\CUSTOM\energetic\block1.png"
COPY redstone.png "materialicons\CUSTOM\energetic\block2.png"
COPY emerald.png "materialicons\CUSTOM\energetic\block3.png"
COPY lapis.png "materialicons\CUSTOM\energetic\block4.png"
COPY iron.png "materialicons\CUSTOM\energetic\block5.png"
COPY diamond.png "materialicons\CUSTOM\energetic\block6.png"

COPY diamond.png "materialicons\CUSTOM\ichorium\block1.png"
COPY redstone.png "materialicons\CUSTOM\ichorium\block2.png"
COPY emerald.png "materialicons\CUSTOM\ichorium\block3.png"
COPY lapis.png "materialicons\CUSTOM\ichorium\block4.png"
COPY iron.png "materialicons\CUSTOM\ichorium\block5.png"
COPY diamond.png "materialicons\CUSTOM\ichorium\block6.png"

COPY diamond.png "materialicons\CUSTOM\Manasteel\block1.png"
COPY redstone.png "materialicons\CUSTOM\Manasteel\block2.png"
COPY emerald.png "materialicons\CUSTOM\Manasteel\block3.png"
COPY lapis.png "materialicons\CUSTOM\Manasteel\block4.png"
COPY iron.png "materialicons\CUSTOM\Manasteel\block5.png"
COPY diamond.png "materialicons\CUSTOM\Manasteel\block6.png"

COPY diamond.png "materialicons\CUSTOM\melodic\block1.png"
COPY redstone.png "materialicons\CUSTOM\melodic\block2.png"
COPY emerald.png "materialicons\CUSTOM\melodic\block3.png"
COPY lapis.png "materialicons\CUSTOM\melodic\block4.png"
COPY iron.png "materialicons\CUSTOM\melodic\block5.png"
COPY diamond.png "materialicons\CUSTOM\melodic\block6.png"

COPY diamond.png "materialicons\CUSTOM\stellar\block1.png"
COPY redstone.png "materialicons\CUSTOM\stellar\block2.png"
COPY emerald.png "materialicons\CUSTOM\stellar\block3.png"
COPY lapis.png "materialicons\CUSTOM\stellar\block4.png"
COPY iron.png "materialicons\CUSTOM\stellar\block5.png"
COPY diamond.png "materialicons\CUSTOM\stellar\block6.png"

COPY diamond.png "materialicons\CUSTOM\universium\block1.png"
COPY redstone.png "materialicons\CUSTOM\universium\block2.png"
COPY emerald.png "materialicons\CUSTOM\universium\block3.png"
COPY lapis.png "materialicons\CUSTOM\universium\block4.png"
COPY iron.png "materialicons\CUSTOM\universium\block5.png"
COPY diamond.png "materialicons\CUSTOM\universium\block6.png"

COPY diamond.png "materialicons\CUSTOM\vibrant\block1.png"
COPY redstone.png "materialicons\CUSTOM\vibrant\block2.png"
COPY emerald.png "materialicons\CUSTOM\vibrant\block3.png"
COPY lapis.png "materialicons\CUSTOM\vibrant\block4.png"
COPY iron.png "materialicons\CUSTOM\vibrant\block5.png"
COPY diamond.png "materialicons\CUSTOM\vibrant\block6.png"

COPY diamond.png "materialicons\CUSTOM\vivid\block1.png"
COPY redstone.png "materialicons\CUSTOM\vivid\block2.png"
COPY emerald.png "materialicons\CUSTOM\vivid\block3.png"
COPY lapis.png "materialicons\CUSTOM\vivid\block4.png"
COPY iron.png "materialicons\CUSTOM\vivid\block5.png"
COPY diamond.png "materialicons\CUSTOM\vivid\block6.png"

COPY diamond.png "materialicons\CUSTOM\WhiteDwarfMatter\block1.png"
COPY redstone.png "materialicons\CUSTOM\WhiteDwarfMatter\block2.png"
COPY emerald.png "materialicons\CUSTOM\WhiteDwarfMatter\block3.png"
COPY lapis.png "materialicons\CUSTOM\WhiteDwarfMatter\block4.png"
COPY iron.png "materialicons\CUSTOM\WhiteDwarfMatter\block5.png"
COPY diamond.png "materialicons\CUSTOM\WhiteDwarfMatter\block6.png"