matchTiles=gregtech:iconsets/UEV_SIDE_CYCLOTRON_SOLENOID gregtech:iconsets/UEV_TOP_CYCLOTRON_SOLENOID
method=ctm
faces=all
tiles=0 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
connect=block
